PUT http://localhost:3003/user
Content-Type: application/json

{
  "name": "Pedro Vitor",
  "nickname": "pedrovs",
  "email": "pedrovs@labenu.com"
}

###

GET http://localhost:3003/user/1

###

POST http://localhost:3003/user/edit/1
Content-Type: application/json

{
  "name": "Astro Dev",
  "nickname": "astrodev",
  "email": "astro@dev.com"
}

###

PUT http://localhost:3003/task
Content-Type: application/json

{
  "title": "Criar banco dos alunos",
  "description": "Devemos criar o banco dos alunos para o módulo do backend",
  "limitDate": "2021-05-31",
  "creatorUserId": "001"
}